name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: app_node/package-lock.json

      # Cambiamos al directorio app_node
      - name: Install dependencies
        working-directory: ./app_node
        run: npm ci

      - name: Build project (if applicable)
        working-directory: ./app_node
        run: npm run build --if-present

      - name: Run tests
        working-directory: ./app_node
        run: npm test
